[mypy]
python_version = 3.12
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = False
disallow_incomplete_defs = False
check_untyped_defs = True
ignore_missing_imports = True
show_error_codes = True
show_column_numbers = True
pretty = True

# 第三方库忽略
[mypy-aiohttp.*]
ignore_errors = True

[mypy-dns.*]
ignore_errors = True

[mypy-bs4.*]
ignore_errors = True

[mypy-lxml.*]
ignore_errors = True

[mypy-validators.*]
ignore_errors = True
